<a href="https://colab.research.google.com/github/kalki81000/Machine-Learning-Revision-Last-2025-/blob/main/support_vector_classifier_on_credit_card_data_with_class_imbalance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv("creditcard.csv")

In [ ]:
#reducing the columns to reduce the run time
df = df[['V1', 'V2', 'V3', 'V4', 'Class']]

In [ ]:
df.columns

Index(['V1', 'V2', 'V3', 'V4', 'Class'], dtype='object')

In [ ]:
df.Class.unique()

array([0, 1], dtype=int64)

In [ ]:
df.dtypes

V1       float64
V2       float64
V3       float64
V4       float64
Class      int64
dtype: object

In [ ]:
df.isna().sum()

V1       0
V2       0
V3       0
V4       0
Class    0
dtype: int64

In [ ]:
df.duplicated().sum()

9144

In [ ]:
df = df.drop_duplicates()


In [ ]:
df.Class.value_counts()

Class
0    275190
1       473
Name: count, dtype: int64

In [ ]:
df_maj = df[df.Class == 0]
df_min = df[df.Class == 1]


In [ ]:
from sklearn.utils import resample
df_maj = resample(df_maj, replace=False, n_samples = 10000, random_state=1)

In [ ]:
df_maj.shape

(10000, 5)

In [ ]:
df_maj.Class.unique()

array([0], dtype=int64)

In [ ]:
df

V1         V2        V3        V4  Class
0       -1.359807  -0.072781  2.536347  1.378155      0
1        1.191857   0.266151  0.166480  0.448154      0
2       -1.358354  -1.340163  1.773209  0.379780      0
3       -0.966272  -0.185226  1.792993 -0.863291      0
4       -1.158233   0.877737  1.548718  0.403034      0
...           ...        ...       ...       ...    ...
284802 -11.881118  10.071785 -9.834783 -2.066656      0
284803  -0.732789  -0.055080  2.035030 -0.738589      0
284804   1.919565  -0.301254 -3.249640 -0.557828      0
284805  -0.240440   0.530483  0.702510  0.689799      0
284806  -0.533413  -0.189733  0.703337 -0.506271      0

[275663 rows x 5 columns]

In [ ]:
from imblearn.over_sampling import SMOTE

ovs = SMOTE()
X, y = ovs.fit_resample(df.drop("Class", axis = 1), df['Class'])

In [ ]:
y

0         0
1         0
2         0
3         0
4         0
         ..
550375    1
550376    1
550377    1
550378    1
550379    1
Name: Class, Length: 550380, dtype: int64

In [ ]:
a = pd.concat([X, y], axis =1)
a = a[a.Class == 1]
df_min = resample(a, replace=False, n_samples = 1000, random_state=1)
df_min.Class.unique()

array([1], dtype=int64)

In [ ]:
df_min.shape

(1000, 5)

In [ ]:
df = pd.concat([df_maj.reset_index(drop=True), df_min.reset_index(drop=True)], axis = 0)

In [ ]:
df.reset_index(drop=True, inplace=True)

In [ ]:
df.shape

(11000, 5)

In [ ]:
df.Class.value_counts()

Class
0    10000
1     1000
Name: count, dtype: int64

In [ ]:
#To handle class imbalance
#oversampling
#undersampling
#SMOTE

In [ ]:
X = df.drop("Class", axis =1)
y = df['Class']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30, random_state=1)

In [ ]:
X_train.shape

(7700, 4)

In [ ]:
from sklearn.svm import SVC
clf = SVC(kernel = 'linear')
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [ ]:
y_pred = clf.predict(X_test)

y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98      3025
           1       0.92      0.71      0.80       275

    accuracy                           0.97      3300
   macro avg       0.95      0.85      0.89      3300
weighted avg       0.97      0.97      0.97      3300

